version: "3"

volumes:
  mongodb_data_container:

services:

#  redis:
#    image: redis:alpine

#  worker:
#    image: schoolofdevops/vote-worker
#    depends_on:
#      - redis

  server:
    image: myselfakshatha/cmad-syslog-server:latest
    restart: always
    ports:
      - 5100:8090

  client:
    image: myselfakshatha/cmad-syslog-client:latest
    ports:
      - 5200:3000
    depends_on:
      - server


#  result:
#    image:   myselfakshatha/vote
#    ports:
#      - 5001:80

